# Generated by Django 2.0 on 2017-12-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptouser',
            name='public_key',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='asset_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
